id: A940019EF
title: Sādhana of the Great Master Vairotsana
type: translation
pechas:
- I611141DA
- I6F315AE3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:44:25.469104
  last_modified_at: 2023-01-04 12:44:25.469124
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I611141DA/25FC: D79D
  I6F315AE3/827A: D79D
